input {
  beats {
    port => 5044
  }
}

filter {
  mutate {
    add_field => { "service_name" => "demoDocker" }
    add_tag   => ["spring-boot"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    # Имя индекса с датой. Kibana будет искать именно его.
    index => "spring-app-logs-%{+YYYY.MM.dd}"
  }
  # Для отладки
# stdout { codec => rubydebug }
}